<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Facades\Validator;

class Bank extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'banks_list';

    protected $fillable = ["id"];

    /**
     * Get the words of the current bank.
     */
    public function words(){
        return $this->hasMany('App\Word', 'bank_id');
    }

    /**
     * Get the pictures of the current bank.
     */
    public function pictures(){
        return $this->hasMany('App\Picture', 'bank_id');
    }


    /**
     * Get the conversation (creator) of the current bank
     * @return HasOne
     */
    public function conversation(){
        return $this->hasOne('App\Conversation', "id", "conversation_id");
    }

    private $rules = [
        'title' => 'required|min:1|max:10',
        'description'  => 'required|min:1|max:3000',
    ];

    public function validator() {
        $v = Validator::make($this->attributes, $this->rules);
        return $v;
    }

    public function save(array $options = []) {
        if($this->validator()->fails())
            return $this;

        return parent::save($options); // TODO: Change the autogenerated stub
    }


}
